In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

In [3]:
torch.cuda.init()

In [4]:
torch.cuda.current_device()

0

In [5]:
torch.cuda.device_count()

1

In [6]:
torch.cuda.memory_allocated() # Monitor CUDA memory occupied by the tensors you allocate

0

In [9]:
# caching memory allocator to speed up memory allocations
# this allows fast memory deallocation without device synchronizations
torch.cuda.memory_reserved() # Monitor caching memory allocated

0

In [10]:
cuda = torch.device('cuda') # Default CUDA device used by PyTorch
cuda

device(type='cuda')

In [11]:
x = torch.tensor([10, 20])
x

tensor([10, 20])

In [12]:
x_default = torch.tensor([10, 20], device=cuda)
x_default

tensor([10, 20], device='cuda:0')

In [13]:
# If working with multiple GPUs, they can be specified based on their index
cuda0 = torch.device('cuda:0')
cuda1 = torch.device('cuda:1')
cuda2 = torch.device('cuda:2')
cuda0, cuda1, cuda2

(device(type='cuda', index=0),
 device(type='cuda', index=1),
 device(type='cuda', index=2))

In [14]:
x0 = torch.tensor([10, 20], device=cuda0)
x0

tensor([10, 20], device='cuda:0')

In [15]:
x1 = torch.tensor([10, 20], device=cuda1) # Throws an error as we currently have only one GPU
x1

RuntimeError: ignored

In [16]:
print(x)
y = x.cuda() # Moves the tensor to CUDA memory
print(y)

tensor([10, 20])
tensor([10, 20], device='cuda:0')


In [17]:
# Changing Cuda device. Throws an error as we have only one GPU
print(torch.cuda.current_device()) # Returns 0 for cuda:0
with torch.cuda.device(1): # Changes from cuda:0 to cuda:1 if cuda:1 is available
  print(torch.cuda.current_device()) # Returns 1 if cuda:1 is available

print(torch.cuda.current_device()) # Returns 0 for cuda:0 as we are outside ocntext manager

0


RuntimeError: ignored

In [18]:
sum = x + y

RuntimeError: ignored

In [20]:
sum = x.cuda() + y
sum

tensor([20, 40], device='cuda:0')

In [21]:
torch.cuda.memory_allocated()

2048

In [22]:
torch.cuda.memory_reserved()

2097152

In [24]:
torch.cuda.empty_cache() # Frees up any unused memory