In [19]:
import torch

print(torch.__version__)

1.10.1


In [20]:
torch.get_default_dtype()

torch.float16

In [21]:
torch.set_default_dtype(torch.float64)
torch.get_default_dtype()

torch.float64

In [22]:
torch.set_default_dtype(torch.int) # Only floats are allowed

TypeError: only floating-point types are supported as the default type

In [23]:
tensor_arr = torch.Tensor([[1, 2, 3], [4, 5, 6]])
print(tensor_arr)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [24]:
torch.is_tensor(tensor_arr)

True

In [25]:
torch.numel(tensor_arr)

6

In [26]:
tensor_uninitialized = torch.Tensor(2, 2)

In [27]:
print(tensor_uninitialized)

tensor([[ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00, 2.7892e+179]])


In [28]:
tensor_initialized = torch.rand(2, 2)
print(tensor_initialized)

tensor([[0.0221, 0.8344],
        [0.7199, 0.3003]])


In [29]:
tensor_int = torch.tensor([5, 3]).type(torch.IntTensor) # Different classes for GPU tensors
print(tensor_int)

tensor([5, 3], dtype=torch.int32)


In [30]:
tensor_short = torch.ShortTensor([5.0, 3.0]) # int16
print(tensor_short)

tensor([5, 3], dtype=torch.int16)


In [31]:
tensor_float = torch.tensor([1.0, 2.0]).type(torch.half) # float16
print(tensor_float)

tensor([1., 2.], dtype=torch.float16)


In [32]:
tensor_fill = torch.full((2, 2), fill_value=3.0)
print(tensor_fill)

tensor([[3., 3.],
        [3., 3.]])


In [33]:
tensor_of_ones = torch.ones([2, 4], dtype=torch.int32)
print(tensor_of_ones)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)


In [34]:
tensor_of_zeros = torch.zeros_like(tensor_of_ones)
print(tensor_of_zeros)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)


In [35]:
tensor_eye = torch.eye(5)
print(tensor_eye)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [37]:
non_zero = torch.nonzero(tensor_eye) # Returns a tensor of non-zero indices
print(non_zero)

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])


In [38]:
i = torch.tensor([
    [0, 1, 1],
    [2, 2, 0]
])
print(i)

tensor([[0, 1, 1],
        [2, 2, 0]])


In [39]:
v = torch.tensor([3, 4, 5], dtype=torch.float32)
print(v)

tensor([3., 4., 5.], dtype=torch.float32)


In [40]:
sparse_tensor = torch.sparse_coo_tensor(i, v, [2, 5])
print(sparse_tensor)

tensor(indices=tensor([[0, 1, 1],
                       [2, 2, 0]]),
       values=tensor([3., 4., 5.]),
       size=(2, 5), nnz=3, dtype=torch.float32, layout=torch.sparse_coo)


In [41]:
print(sparse_tensor.to_dense())

tensor([[0., 0., 3., 0., 0.],
        [5., 0., 4., 0., 0.]], dtype=torch.float32)


In [42]:
initial_tensor = torch.rand(2, 3)
print(initial_tensor)

tensor([[7.8317e-04, 7.3808e-01, 8.7915e-01],
        [4.3542e-01, 1.7453e-01, 4.8800e-02]])


In [49]:
initial_tensor.fill_(10) # Operations that modify the tensor in-place have a trailing underscore

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [50]:
initial_tensor.fill(10) # Not all operations have both types of functions (in-place vs. out-of-place)
# fill does not have out of place function

AttributeError: 'Tensor' object has no attribute 'fill'

In [51]:
new_tensor = initial_tensor.add(5)
print(new_tensor)

tensor([[15., 15., 15.],
        [15., 15., 15.]])


In [52]:
initial_tensor

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [53]:
new_tensor = initial_tensor.add_(5) # In-place operations have a trailing underscore
print(initial_tensor)

tensor([[15., 15., 15.],
        [15., 15., 15.]])


In [54]:
new_tensor.sqrt_()
print(new_tensor)

tensor([[3.8730, 3.8730, 3.8730],
        [3.8730, 3.8730, 3.8730]])


In [55]:
x = torch.linspace(start=0.1, end=10, steps=15)
print(x)

tensor([ 0.1000,  0.8071,  1.5143,  2.2214,  2.9286,  3.6357,  4.3429,  5.0500,
         5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])


In [57]:
tensor_chunk = torch.chunk(x, chunks=3, dim=0)
print(type(tensor_chunk))
print(tensor_chunk)

<class 'tuple'>
(tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286]), tensor([3.6357, 4.3429, 5.0500, 5.7571, 6.4643]), tensor([ 7.1714,  7.8786,  8.5857,  9.2929, 10.0000]))


In [58]:
tensor1 = tensor_chunk[0]
tensor2 = tensor_chunk[1]
tensor3 = torch.tensor([3.0, 4.0, 5.0])
torch.cat((tensor1, tensor2, tensor3), dim=0)

tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286, 3.6357, 4.3429, 5.0500, 5.7571,
        6.4643, 3.0000, 4.0000, 5.0000])

In [61]:
random_tensor = torch.Tensor([[10, 8, 30], [40, 5, 6], [12, 2, 21]])
print(random_tensor)

tensor([[10.,  8., 30.],
        [40.,  5.,  6.],
        [12.,  2., 21.]])


In [62]:
random_tensor[0, 1]

tensor(8.)

In [63]:
random_tensor[1:, 1:]

tensor([[ 5.,  6.],
        [ 2., 21.]])

In [64]:
random_tensor.size()

torch.Size([3, 3])

In [65]:
resized_tensor = random_tensor.view(9)
print(resized_tensor)

tensor([10.,  8., 30., 40.,  5.,  6., 12.,  2., 21.])


In [67]:
random_tensor[2, 2] = 100
print(resized_tensor) # This is a view of the original tensor. 
# Any changes to the original tensor will be reflected in the view

tensor([ 10.,   8.,  30.,  40.,   5.,   6.,  12.,   2., 100.])


In [68]:
random_tensor.shape

torch.Size([3, 3])

In [69]:
tensor_unsqueeze = torch.unsqueeze(random_tensor, dim=2)
print(tensor_unsqueeze)

tensor([[[ 10.],
         [  8.],
         [ 30.]],

        [[ 40.],
         [  5.],
         [  6.]],

        [[ 12.],
         [  2.],
         [100.]]])


In [70]:
tensor_unsqueeze.shape

torch.Size([3, 3, 1])

In [72]:
print(initial_tensor)
tensor_transpose = initial_tensor.transpose(dim0=0, dim1=1)
print(tensor_transpose)

tensor([[3.8730, 3.8730, 3.8730],
        [3.8730, 3.8730, 3.8730]])
tensor([[3.8730, 3.8730],
        [3.8730, 3.8730],
        [3.8730, 3.8730]])


In [74]:
sorted_tensor, sorted_indices = torch.sort(random_tensor)
print(sorted_tensor)
print(sorted_indices)

tensor([[  8.,  10.,  30.],
        [  5.,   6.,  40.],
        [  2.,  12., 100.]])
tensor([[1, 0, 2],
        [1, 2, 0],
        [1, 0, 2]])


In [75]:
tensor_float = torch.FloatTensor([-1.1, -2.2, 3.3])
print(tensor_float)

tensor([-1.1000, -2.2000,  3.3000], dtype=torch.float32)


In [76]:
tensor_abs = torch.abs(tensor_float)
print(tensor_abs)

tensor([1.1000, 2.2000, 3.3000], dtype=torch.float32)


In [77]:
rand1 = torch.abs(torch.randn(2, 3))
rand2 = torch.abs(torch.randn(2, 3))
print(rand1)
print(rand2)

tensor([[1.3433, 0.2671, 0.1038],
        [1.1307, 0.0725, 0.7963]])
tensor([[0.5276, 2.1135, 0.1861],
        [0.7776, 0.8169, 0.7624]])


In [78]:
add1 = rand1 + rand2
print(add1)

tensor([[1.8709, 2.3806, 0.2899],
        [1.9083, 0.8894, 1.5587]])


In [80]:
add2 = torch.add(rand1, rand2)
print(add2)

tensor([[1.8709, 2.3806, 0.2899],
        [1.9083, 0.8894, 1.5587]])


In [79]:
tensor = torch.Tensor(
    [
        [-1, -2, -3],
        [1, 2, 3]
    ]
)
print(tensor)

tensor([[-1., -2., -3.],
        [ 1.,  2.,  3.]])


In [81]:
tensor_div = torch.div(tensor, tensor + 0.3)
print(tensor_div)

tensor([[1.4286, 1.1765, 1.1111],
        [0.7692, 0.8696, 0.9091]])


In [82]:
tensor_mul = torch.mul(tensor, tensor)
print(tensor_mul)

tensor([[1., 4., 9.],
        [1., 4., 9.]])


In [83]:
tensor_clamp = torch.clamp(tensor, min=-0.2, max=2)
print(tensor_clamp)

tensor([[-0.2000, -0.2000, -0.2000],
        [ 1.0000,  2.0000,  2.0000]])


In [84]:
t1 = torch.Tensor([1, 2])
t2 = torch.Tensor([10, 20])
dot_product = torch.dot(t1, t2)
print(dot_product)

tensor(50.)


In [85]:
matrix = torch.Tensor([
    [1, 2, 3],
    [4, 5, 6]
])
vector = torch.Tensor([0, 1, 2])
matrix_vector = torch.mv(matrix, vector)
print(matrix_vector)

tensor([ 8., 17.])


In [86]:
another_matrix = torch.Tensor([
    [10, 30],
    [20, 0],
    [0, 50]
])
matrix_mul = torch.mm(matrix, another_matrix)
print(matrix_mul)

tensor([[ 50., 180.],
        [140., 420.]])


In [87]:
torch.argmax(matrix_mul, dim=0)

tensor([1, 1])

In [88]:
torch.argmin(matrix_mul, dim=1)

tensor([0, 0])

In [89]:
import numpy as np

In [90]:
numpy_from_tensor = np.array(tensor)
print(numpy_from_tensor)
print(type(numpy_from_tensor))

[[-1. -2. -3.]
 [ 1.  2.  3.]]
<class 'numpy.ndarray'>


In [91]:
print(torch.is_tensor(numpy_from_tensor))

False


In [93]:
numpy_from_tensor

array([[100.,  -2.,  -3.],
       [  1.,   2.,   3.]])